### ISSUE TITLE
iOS14 崩溃

### ISSUE THREAD

**Issue by adolph-suntao** [fanfay/RichEdit#3]
objc[18067]: no class for metaclass 0x600000bb4b10
CoreSimulator 732.17 - Device: iPhone 11 (CCD798DB-BC2C-441F-AA6C-5D411B201D1F) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11

**Comment by adolph-suntao** [comment]
定位到  FauxBarHelper().removeInputAccessoryView(webView: webView) 这行代码崩溃

**Comment by kedu** [comment]
我这也是。跑起来一点就崩溃

**Comment by fanfay** [comment]
crash 已经修复
